import oracledb from 'oracledb'
import { serverConfig } from '../../config/environment.js'

oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT

const getConnection = async () =>
  oracledb.getConnection({
    user: serverConfig.oracle.user,
    password: serverConfig.oracle.password,
    connectString: serverConfig.oracle.connectionString,
  })

const mapRow = (row) => ({
  id: row.id,
  name: row.name,
  autismPoints: row.autismPoints,
  alcoholPoints: row.alcoholPoints,
  yellowCards: row.yellowCards,
})

const findPersonById = async (connection, personId) => {
  const result = await connection.execute(
    `
      SELECT
        ID AS "id",
        NAME AS "name",
        AUTISM_POINTS AS "autismPoints",
        ALCOHOL_POINTS AS "alcoholPoints",
        YELLOW_CARDS AS "yellowCards"
      FROM PEOPLE_RANKING
      WHERE ID = :id
    `,
    { id: personId },
  )

  return result.rows?.[0] ?? null
}

export const createOraclePeopleRepository = () => ({
  async init() {
    const connection = await getConnection()

    try {
      await connection.execute(`
        CREATE TABLE PEOPLE_RANKING (
          ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          NAME VARCHAR2(120) NOT NULL,
          AUTISM_POINTS NUMBER(10) DEFAULT 0 NOT NULL,
          ALCOHOL_POINTS NUMBER(10) DEFAULT 0 NOT NULL,
          YELLOW_CARDS NUMBER(10) DEFAULT 0 NOT NULL,
          CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )
      `)
      await connection.commit()
    } catch (error) {
      if (error.errorNum !== 955) {
        throw error
      }
    } finally {
      await connection.close()
    }
  },

  async listPeople() {
    const connection = await getConnection()

    try {
      const result = await connection.execute(`
        SELECT
          ID AS "id",
          NAME AS "name",
          AUTISM_POINTS AS "autismPoints",
          ALCOHOL_POINTS AS "alcoholPoints",
          YELLOW_CARDS AS "yellowCards"
        FROM PEOPLE_RANKING
        ORDER BY CREATED_AT ASC
      `)

      return result.rows ?? []
    } finally {
      await connection.close()
    }
  },

  async createPerson({ name, autismPoints, alcoholPoints, yellowCards }) {
    const connection = await getConnection()

    try {
      const result = await connection.execute(
        `
        INSERT INTO PEOPLE_RANKING (NAME, AUTISM_POINTS, ALCOHOL_POINTS, YELLOW_CARDS)
        VALUES (:name, :autismPoints, :alcoholPoints, :yellowCards)
        RETURNING ID INTO :id
        `,
        {
          name,
          autismPoints,
          alcoholPoints,
          yellowCards,
          id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER },
        },
      )

      await connection.commit()

      return {
        id: result.outBinds.id[0],
        name,
        autismPoints,
        alcoholPoints,
        yellowCards,
      }
    } finally {
      await connection.close()
    }
  },

  async updatePerson(personId, payload) {
    const connection = await getConnection()

    try {
      const result = await connection.execute(
        `
          UPDATE PEOPLE_RANKING
          SET
            NAME = COALESCE(:name, NAME),
            AUTISM_POINTS = COALESCE(:autismPoints, AUTISM_POINTS),
            ALCOHOL_POINTS = COALESCE(:alcoholPoints, ALCOHOL_POINTS),
            YELLOW_CARDS = COALESCE(:yellowCards, YELLOW_CARDS)
          WHERE ID = :id
        `,
        {
          id: personId,
          name: Object.hasOwn(payload, 'name') ? payload.name : null,
          autismPoints: Object.hasOwn(payload, 'autismPoints') ? payload.autismPoints : null,
          alcoholPoints: Object.hasOwn(payload, 'alcoholPoints') ? payload.alcoholPoints : null,
          yellowCards: Object.hasOwn(payload, 'yellowCards') ? payload.yellowCards : null,
        },
      )

      if ((result.rowsAffected ?? 0) === 0) {
        return null
      }

      const row = await findPersonById(connection, personId)
      await connection.commit()

      return row ? mapRow(row) : null
    } finally {
      await connection.close()
    }
  },

  async deletePerson(personId) {
    const connection = await getConnection()

    try {
      const result = await connection.execute('DELETE FROM PEOPLE_RANKING WHERE ID = :id', { id: personId })
      await connection.commit()

      return (result.rowsAffected ?? 0) > 0
    } finally {
      await connection.close()
    }
  },
})
